### ISSUE TITLE
Config files location

### ISSUE THREAD

**Issue by dfdalamar** [logstash-plugins/logstash-input-snmp#10]
Hi,

I just installed the plugin and I am looking for the location of the config files.  I have checked the modules and the plugin folders to see if I could find them.  I have also looked in the config folder for logstash.  I would like to point the configs to snmp traps already being gathered as a way to port the information over to ELK.  I am currently collecting the information in a tool called librenms and getting all the stats for that using rrd.

**Comment by colinsurprenant** [comment]
Hello @dfdalamar 

> I just installed the plugin and I am looking for the location of the config files.

Which config files? The only configuration options are those in the input plugin options part of the logstash configuration. 

If you are talking about the MIB files, none are provided with the plugin yet. Let me know if this is what you are talking about and I will walk you through the way to use them (it is mentioned [in the wiki page](https://github.com/logstash-plugins/logstash-input-snmp/wiki))

**Comment by dfdalamar** [comment]
Colin,
So I would create a new pipeline and then point it to the conf file.  That makes sense.  Thank you!!  

I have a directory full of MIB files I would like to use.  How do I tell the collector to use those MIBS?

**Comment by colinsurprenant** [comment]
@dfdalamar so for MIB file, currently they can only be used for translating OIDs to field names.  You will still need to specify your `get` or `walk` OIDs in the configuration.

To use a MIB file, as described [in the wiki](https://github.com/logstash-plugins/logstash-input-snmp/wiki) you first have to convert the MIB file to be usable with logstash and to do so you have to install the open source [libsmi library](https://www.ibr.cs.tu-bs.de/projects/libsmi/).

When it is installed you need to do the following for each MIB file you want to use, for example if your MIB file is `RFC1213-MIB.txt`:
```
$ smidump -k -f python RFC1213-MIB.txt > /path/to/converted/mibfiles/RFC1213-MIB.dic
```

The resulting file `RFC1213-MIB.dic` can be placed in a directory somewhere (let's say `/path/to/converted/mibfiles/`) and you need to point your config to this directory using the `mibpaths` option like this:
```
input {
  snmp {
    ...
    mib_paths => ["/path/to/converted/mibfiles/"]
  }
}
```

**Comment by colinsurprenant** [comment]
@dfdalamar I wanted to circle back to see if you had success with the MIB files handling, if it was useful or maybe not what you were expecting? Thanks.

**Comment by dfdalamar** [comment]
I am still working on how to convert them to dic files.  Because my MIB files are not txt. I need to find a bulk thing.  I am still working on it though.  Thanks for checking!!!

**Comment by colinsurprenant** [comment]
@dfdalamar the actual file name and extension of your MIB file(s) is not important, this was just an example above. Just pass the actual name of your MIB file and  make sure that the resulting converted MIB file has the `.dic` extension. Let me know if this is not clear.

**Comment by dfdalamar** [comment]
Hi.  My MIB files did not have an extension.  I ran this command to fix that.
rename 's/(.*)/$1.lic/' *

My conf file looks like this and I am testing:

```
input {
  snmp {
    walk => ["1.3.6.1"]
    mib_paths => ["/etc/logstash/MIB/*.dic"]
    hosts => [{host => "udp:192.168.xxx.xxx/161" community => "*****"}]
  }
}

output {
  elasticsearch {
    hosts => [ "127.0.0.1:9200" ]
    index => "ASA-SNMP-%{+YYYY.MM.dd}"
  }
}
```

**Comment by dfdalamar** [comment]
My config won't work.  I got the following error.

```
[2018-06-13T16:34:27,907][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"snmp", :plugin=>"<LogStash::Inputs::Snmp walk=>[\"1.3.6.1\"], mib_paths=>[\"/etc/logstash/MIB/*.dic\"], hosts=>[{\"host\"=>\"udp:192.168.xxx.xxx/161\", \"community\"=>\"*****\"}],id=>\"44f03ff74b7fd36f29ea2e42c66bd870cab4700e38e7942160e906a60afa355e\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_c14f9992-b4e6-4ed0-a492-b052b4a884e8\", enable_metric=>true, charset=>\"UTF-8\">, add_field=>{\"host\"=>\"%{[@metadata][host_address]}\"}, oid_root_skip=>0, interval=>30>", :error=>"file or directory path expected: /etc/logstash/MIB/*.dic", :thread=>"#<Thread:0x48b6900d run>"}
[2018-06-13T16:34:28,752][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"snmp", :exception=>#<LogStash::SnmpMibError: file or directory path expected: /etc/logstash/MIB/*.dic>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/mib.rb:101:in `add_mib_path'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:66:in `block in register'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:64:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:500:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:394:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"], :thread=>"#<Thread:0x48b6900d run>"}
[2018-06-13T16:34:28,790][ERROR][logstash.agent           ] Failed to execute action {:id=>:snmp, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:snmp, action_result: false", :backtrace=>nil}
```

There are a couple of MIB files I have I want it to use.  I have the standard IF-MB file but I also have Cisco specific MIB files I want it to use.  How would I specify the MIBS to use?

**Comment by colinsurprenant** [comment]
@dfdalamar  ok easy to fix, the `mib_paths` option does not support globs so either list all individual files or just put the directory and it will grab all `*.dic` files :
```
input {
  snmp {
    walk => ["1.3.6.1"]
    mib_paths => ["/etc/logstash/MIB/"]
    hosts => [{host => "udp:192.168.xxx.xxx/161" community => "*****"}]
  }
}
```

Let me know how that work for you.

**Comment by dfdalamar** [comment]
Now I have this error.  I am not getting any output to elasticsearch.

```
[2018-06-13T17:16:01,457][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:16:34,040][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:17:07,562][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:17:39,377][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:18:10,637][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}

```

**Comment by colinsurprenant** [comment]
@dfdalamar ok thanks for your perseverance here!  S
Since this is a different issue, I'll go ahead and create a new issue for it and we can follow over there. It should be an easy fix.

We can keep this issue open until we confirm that your MIB files are being used correctly.

**Comment by colinsurprenant** [comment]
@dfdalamar that error should now be fixed per #11 - can you update the plugin to version `0.1.0.beta4` and let me know how it works in issue #11 ? Thanks.

**Comment by colinsurprenant** [comment]
@dfdalamar  per the log you provided you still have version `0.1.0.beta3` installed, the fixed I made is included in `0.1.0.beta4`. You can install it like this:

```sh
$ bin/logstash-plugin install --version 0.1.0.beta4 logstash-input-snmp
```

**Comment by colinsurprenant** [comment]
@dfdalamar ok, now that the plugin is updated, when you stop and restart logstash, do you still see the `SnmpClientError: unknown variable syntax 70, Counter64` errors?

**Comment by dfdalamar** [comment]
Colin,

[2018-06-21T13:16:54,666][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
``

Even though it is updated it is still using the old library.
librenms@librenms:/usr/share/logstash/bin$ sudo ./logstash-plugin list --verbose
logstash-input-snmp (0.1.0.beta4)
librenms@librenms:/usr/share/logstash/bin$ sudo service logstash status
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/logstash.service.d
           └─elastiflow.conf
   Active: active (running) since Thu 2018-06-21 13:17:44 EDT; 1h 32min ago
 Main PID: 23323 (java)
    Tasks: 49
   Memory: 2.5G
      CPU: 4h 28min 6.776s
   CGroup: /system.slice/logstash.service
           └─23323 /usr/bin/java -Xms2g -Xmx2g -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encoding=UTF-8

**Comment by colinsurprenant** [comment]
@dfdalamar oh this is weird indeed. I will try to reproduce here see what can be causing this but in the mean time you could try 
```
bin/logstash-plugin remove logstash-input-snmp
```
and then reinstall version 0.1.0.beta4 see if that works.

**Comment by colinsurprenant** [comment]
@dfdalamar any progress over this?
