### ISSUE TITLE
SnmpClientError: unknown variable syntax 70, Counter64

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-snmp#11]
As reported by @dfdalamar in #10  We seem to be missing some type coercion for syntax 70, `Counter64`. 

```
[2018-06-13T17:16:01,457][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:16:34,040][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:17:07,562][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:17:39,377][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}
[2018-06-13T17:18:10,637][ERROR][logstash.inputs.snmp     ] error invoking walk operation on OID: 1.3.6.1, ignoring {:exception=>#<LogStash::SnmpClientError: unknown variable syntax 70, Counter64>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:124:in `coerce'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:96:in `block in walk'", "org/jruby/java/proxies/ArrayJavaProxy.java:450:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:91:in `block in walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp/client.rb:80:in `walk'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:118:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:116:in `block in run'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta3/lib/logstash/inputs/snmp.rb:106:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'"]}

```

**Comment by colinsurprenant** [comment]
@dfdalamar this should now be fixed, you can install version `0.1.0.beta4`
