### ISSUE TITLE
Compiling/install problems

### ISSUE THREAD

**Issue by eperry** [logstash-plugins/logstash-input-snmp#41]
The build documentation seems to be too generic and I can't seem to figure out what I am doing wrong

some assist. What am I missing?

I try doing a bundle install but that seems to fail.

```
eperry@coperdragon:~/logstash-input-snmp$ bundle install
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Fetching source index from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
```

Throws warnings but successful build
```
eperry@coperdragon:~/logstash-input-snmp$ gem build logstash-input-snmp.gemspec ; WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
WARNING:  open-ended dependency on logstash-codec-plain (>= 0) is not recommended
  if logstash-codec-plain is semantically versioned, use:
    add_runtime_dependency 'logstash-codec-plain', '~> 0'
WARNING:  open-ended dependency on logstash-devutils (>= 0, development) is not recommended
  if logstash-devutils is semantically versioned, use:
    add_development_dependency 'logstash-devutils', '~> 0'
WARNING:  open-ended dependency on rspec-wait (>= 0, development) is not recommended
  if rspec-wait is semantically versioned, use:
    add_development_dependency 'rspec-wait', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: logstash-input-snmp
  Version: 1.0.2
  File: logstash-input-snmp-1.0.2.gem
```
Install succeds
```
~/Downloads/logstash-test-6.4.2/bin/logstash-plugin install --no-verify ./logstash-input-snmp-1.0.2.gem ;
Installing logstash-input-snmp
Installation successful
```

**But trying to run logstash it seems to be problematic**
```
 ~/Downloads/logstash-test-6.4.2/bin/logstash -f l.conf --config.reload.automatic
Sending Logstash's logs to /home/eperry/Downloads/logstash-test-6.4.2/logs which is now configured via log4j2.properties
[2018-11-03T17:32:52,357][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/home/eperry/Downloads/logstash-test-6.4.2/modules/fb_apache/configuration"}
[2018-11-03T17:32:52,393][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/home/eperry/Downloads/logstash-test-6.4.2/modules/netflow/configuration"}
[2018-11-03T17:32:53,128][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-11-03T17:32:53,957][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.4"}
[2018-11-03T17:32:54,508][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-11-03T17:32:57,216][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"input", :name=>"snmp", :path=>"logstash/inputs/snmp", :error_message=>"\n\n\tyou might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\nno such file to load -- org/snmp4j/snmp4j/2.5.11/snmp4j-2.5.11 (LoadError)", :error_class=>RuntimeError, :error_backtrace=>["/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.12/lib/jar_dependencies.rb:344:in `do_require'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.12/lib/jar_dependencies.rb:253:in `block in require_jar'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.12/lib/jar_dependencies.rb:295:in `require_jar_with_block'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.12/lib/jar_dependencies.rb:252:in `require_jar'", "/home/eperry/Downloads/logstash-test-6.4.2/lib/bootstrap/patches/jar_dependencies.rb:6:in `require_jar'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/local_gems/1a96cf80/logstash-input-snmp-1.0.2/lib/logstash-input-snmp_jars.rb:4:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/local_gems/1a96cf80/logstash-input-snmp-1.0.2/lib/logstash/inputs/snmp/client.rb:1:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'", "uri:classloader:/jruby/kernel/kernel.rb:13:in `require_relative'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/local_gems/1a96cf80/logstash-input-snmp-1.0.2/lib/logstash/inputs/snmp/client.rb:2:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugins/registry.rb:162:in `legacy_lookup'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugins/registry.rb:140:in `lookup'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugins/registry.rb:187:in `lookup_pipeline_plugin'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugins/plugin_factory.rb:81:in `plugin'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline.rb:112:in `plugin'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/local_gems/1a96cf80/logstash-input-snmp-1.0.2/lib/logstash/inputs/snmp.rb:1:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline.rb:84:in `initialize'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline.rb:169:in `initialize'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:315:in `block in converge_state'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:312:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:299:in `converge_state'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/runner.rb:348:in `block in execute'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
[2018-11-03T17:32:57,281][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any input plugin named 'snmp'. Are you sure this is correct? Trying to load the snmp input plugin resulted in this error: Problems loading the requested plugin named snmp of type input. Error: RuntimeError \n\n\tyou might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\nno such file to load -- org/snmp4j/snmp4j/2.5.11/snmp4j-2.5.11 (LoadError)", :backtrace=>["/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugins/registry.rb:192:in `lookup_pipeline_plugin'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/plugins/plugin_factory.rb:81:in `plugin'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline.rb:112:in `plugin'", "(eval):8:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline.rb:84:in `initialize'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline.rb:169:in `initialize'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:315:in `block in converge_state'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:312:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:299:in `converge_state'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/home/eperry/Downloads/logstash-test-6.4.2/logstash-core/lib/logstash/runner.rb:348:in `block in execute'", "/home/eperry/Downloads/logstash-test-6.4.2/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
^C[2018-11-03T17:32:59,058][WARN ][logstash.runner          ] SIGINT received. Shutting down.

**Comment by eperry** [comment]
Like I figured, the issue was with my enviroment. There is something wrong with ssl.

It seems like I have some old jruby rvm's . Closing this as it is all me.
