### ISSUE TITLE
[ERROR][logstash.inputs.snmp] Unknown setting 'tables' for snmp

### ISSUE THREAD

**Issue by piellick** [logstash-plugins/logstash-input-snmp#73]
Hello,

i'm trying to use tables option to query tabular values from an OID, when i create th logstash configuration, i have this error : 

```
>  OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
> Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
> [2020-03-17T12:42:45,328][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
> [2020-03-17T12:42:45,356][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
> [2020-03-17T12:42:46,265][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.8.1"}
> [2020-03-17T12:42:46,295][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"20cb89e9-2f5d-4922-9c5f-d61ea50b5410", :path=>"/usr/share/logstash/data/uuid"}
> [2020-03-17T12:42:46,968][WARN ][logstash.monitoringextension.pipelineregisterhook] xpack.monitoring.enabled has not been defined, but found elasticsearch configuration. Please explicitly set `xpack.monitoring.enabled: true` in logstash.yml
> [2020-03-17T12:42:48,543][ERROR][logstash.monitoring.internalpipelinesource] Failed to fetch X-Pack information from Elasticsearch. This is likely due to failure to reach a live Elasticsearch cluster.
> [2020-03-17T12:42:55,342][ERROR][logstash.inputs.snmp     ] Unknown setting 'tables' for snmp
> [2020-03-17T12:42:55,357][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Something is wrong with your configuration.", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/config/mixin.rb:86:in `config_init'", "/usr/share/logstash/logstash-core/lib/logstash/inputs/base.rb:60:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:255:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:184:in `plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "(eval):8:in `initialize'", "org/jruby/RubyKernel.java:1061:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:43:in `block in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:96:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:165:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:96:in `exclusive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:39:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:334:in `block in converge_state'"]}
> [2020-03-17T12:42:55,903][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
> [2020-03-17T12:43:00,570][INFO ][logstash.runner          ] Logstash shut down.
> 
> 
```

Here is my logstash configuration:

```
input {

#    snmp {
#	mib_paths => ["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-snmp-1.0.1/lib/mibs/infinera/"]
#    walk => [".1.3.6.1.4.1.8708.2.1.2.2"]
#    hosts => [{host => "udp:XXXXXX/161" community => "XXXXXX" retries => 2  timeout => 30}]
#	oid_root_skip => 6
#    interval => 300
#  }
  
  snmp {
  hosts => [{host => "udp:XXXXXXX/161" community => "XXXXXX" retries => 2  timeout => 30}]
  tables => [{"name" => "infinera_alarmes" "columns" => [".1.3.6.1.4.1.8708.2.1.2.2.1.1"]}]
  }
}

output {
elasticsearch {
       hosts => ["http://es-cluster-0:9200","http://es-cluster-1:9200","http://es-cluster-2:9200","http://es-cluster-3:9200"]
         index => "infinera-%{+YYYY.MM.dd}"
        }	
      stdout {}
}
```

logstash from elastic docker hub version : 6.8.1 and snmp plugin installed (WALK option work well!).

Any idea ?

Thanks

**Comment by piellick** [comment]
Using now version 6.8.7 of docker registry with the latest version of plugin and it's work.

You can close it.

**Comment by colinsurprenant** [comment]
Thanks for you feedback @piellick. Will close.
