### ISSUE TITLE
Snmp logstash - uninitialized constant

### ISSUE THREAD

**Issue by jangel97** [logstash-plugins/logstash-input-snmp#91]
Hello there,

I am trying to monitor a cisco device via snmp with logstash. In order to do so, I am using the following configuration file:
```
input {
        snmp {
                hosts => [{host => "udp:192.168.28.210/161" community => "user_ro" version => "2c"  retries => 2  timeout => 1000}]
                tables => [ {"name" => "interfaces" "columns" => ["1.3.6.1.2.1.2.2.1.1", "1.3.6.1.2.1.2.2.1.2", "1.3.6.1.2.1.2.2.1.5", "1.3.6.1.2.1.31.1.1.1.6", "1.3. .1.2.1.31.1.1.1.10"]} ]
        }
}

output {
        stdout {
                codec => rubydebug
        }
}
```
As it is mentioned in the documentation I ensured the library *libsmi* is installed in the system. And I also installed the plugin logstash-input-snmp through the next command: `/usr/share/logstash/bin/logstash-plugin install logstash-input-snmp`

Information:
- **logstash version**: 7.9.2
- **snmp server version**: 2c
- **command to test config file**: */usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/10_input.conf --log.level=debug --path.settings=/etc/logstash*
- **community string has READ ONLY permissions**

The error seems to be the following:
```
 org.logstash.config.ir.compiler.ComputeStepSyntaxElement@3fdc2b9c
[2020-10-15T11:52:35,838][DEBUG][org.logstash.config.ir.CompiledPipeline][main] Compiled output
 P[output-stdout{"codec"=>"rubydebug"}|[file]/etc/logstash/conf.d/10_input.conf:9:2:```
stdout {
                codec => rubydebug
        }
```] 
 into 
 org.logstash.config.ir.compiler.ComputeStepSyntaxElement@3fdc2b9c
[2020-10-15T11:52:36,017][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.9}
[2020-10-15T11:52:36,119][DEBUG][logstash.javapipeline    ][main] Shutdown waiting for worker thread {:pipeline_id=>"main", :thread=>"#<Thread:0x59fba3d5 run>"}
[2020-10-15T11:52:36,243][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2020-10-15T11:52:36,244][DEBUG][logstash.javapipeline    ][main] Shutdown waiting for worker thread {:pipeline_id=>"main", :thread=>"#<Thread:0x31b5ed6e dead>"}
[2020-10-15T11:52:36,246][DEBUG][logstash.javapipeline    ][main] Shutdown waiting for worker thread {:pipeline_id=>"main", :thread=>"#<Thread:0x25416db5 dead>"}
[2020-10-15T11:52:36,250][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
[2020-10-15T11:52:36,258][DEBUG][logstash.outputs.stdout  ][main] Closing {:plugin=>"LogStash::Outputs::Stdout"}
[2020-10-15T11:52:36,267][DEBUG][logstash.pluginmetadata  ][main] Removing metadata for plugin 54b0766bb8b169cfac8d7b0617ba65335f31699fbac73909eaae70d5e1c362f4
[2020-10-15T11:52:36,274][DEBUG][logstash.javapipeline    ][main] Pipeline terminated by worker error {:pipeline_id=>"main", :exception=>#<NameError: uninitialized constant LogStash::Inputs::Snmp::Logstash>, :backtrace=>["org/jruby/RubyModule.java:3760:in `const_missing'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-snmp-1.2.5/lib/logstash/inputs/snmp.rb:254:in `block in validate_oids!'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-snmp-1.2.5/lib/logstash/inputs/snmp.rb:252:in `block in validate_oids!'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-snmp-1.2.5/lib/logstash/inputs/snmp.rb:249:in `validate_oids!'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-snmp-1.2.5/lib/logstash/inputs/snmp.rb:101:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:226:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:225:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:359:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:309:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:183:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:134:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/10_input.conf"], :thread=>"#<Thread:0x5e76a872 run>"}
[2020-10-15T11:52:36,300][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2020-10-15T11:52:36,372][DEBUG][logstash.agent           ] Starting puma
[2020-10-15T11:52:36,387][DEBUG][logstash.instrument.periodicpoller.os] Stopping
[2020-10-15T11:52:36,393][DEBUG][logstash.agent           ] Trying to start WebServer {:port=>9600}
[2020-10-15T11:52:36,410][DEBUG][logstash.instrument.periodicpoller.jvm] Stopping
[2020-10-15T11:52:36,413][DEBUG][logstash.instrument.periodicpoller.persistentqueue] Stopping
[2020-10-15T11:52:36,414][DEBUG][logstash.instrument.periodicpoller.deadletterqueue] Stopping
[2020-10-15T11:52:36,435][DEBUG][logstash.agent           ] Shutting down all pipelines {:pipelines_count=>0}
[2020-10-15T11:52:36,438][DEBUG][logstash.agent           ] Converging pipelines state {:actions_count=>0}
[2020-10-15T11:52:36,450][DEBUG][logstash.api.service     ] [api-service] start
[2020-10-15T11:52:36,621][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2020-10-15T11:52:41,515][INFO ][logstash.runner          ] Logstash shut down.
[2020-10-15T11:52:41,535][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```
Link to full log: https://pastebin.com/1aUeQL1N
 
Is there anything I am missing? Is it failing because of some dependency issue?

Thanks in advance,

Reference: https://discuss.elastic.co/t/snmp-logstash-error/252163

**Comment by jangel97** [comment]
Okay I just realized my typo at the very beginning. Sorry for any inconvinience,
